### ISSUE TITLE
Sequentialized DNS lookup implementation

### ISSUE THREAD

**Issue by marklrh** [janestreet/async_unix#4]
At [line 237 of unix_syscalls.mli](https://github.com/janestreet/async_unix/blob/master/lib/unix_syscalls.mli#L327), seems that DNS lookup has been sequentialized due to some thread safety issue. 

I talked to Yaron in the IRC and he said 
> The winbind issue looks like an old one to me.  I think we don’t rely on winbind anymore, but I’m not sure.  In any case, we can probably make the degree of parallelism tuneable.

Is it possible to make some improvement on it?

Thanks

**Comment by diml** [comment]
We discussed it and it turns out we don't need to sequentialize DNS lookups anymore. So this will be removed in the next release.
