### ISSUE TITLE
Extracting exception raised from inner monitor in writer

### ISSUE THREAD

**Issue by copy** [janestreet/async_unix#9]
In [writer0.ml line 439](https://github.com/janestreet/async_unix/blob/2e1b0f9a448c1398901f0768d805ccea35cae999/src/writer0.ml#L469), exceptions raised in the inner monitor are wrapped into `Error`. Is there a way to extract the original exception or handle this exception in another way? `Error` seems to be there only to provide human-readable messages.

I would like to ignore broken pipes exceptions like this:

```
(src/monitor.ml.Error_
  ((exn
     ("writer error"
       ((src/monitor.ml.Error_
          ((exn (Unix.Unix_error "Broken pipe" writev "")) (backtrace (""))
            (monitor
              (((name (id 39)) (here ()) (id 39) (has_seen_error true)
[…]
```

**Comment by diml** [comment]
Note that for this particular problem, you can use `~raise_when_consumer_leave:false` when creating the writer, and you can use `Writer.consumer_left` to be notified.

For you original question, you can't extract the original unix error. We usually don't match on exceptions directly

**Comment by copy** [comment]
> Note that for this particular problem, you can use ~raise_when_consumer_leave:false when creating the writer, and you can use Writer.consumer_left to be notified.

This works for me, thanks.
